<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="USPUNKAINGAL12" failures="1" tests="1" name="Default test" time="14.428" errors="0" timestamp="2025-07-04T15:23:24 IST">
  <testcase classname="com.tests.scenario5.TC_01_ChkOutFunc_ValidateCheckoutFunctionalityTest" name="verifyCheckoutFunctionlity" time="1.792">
    <failure type="java.lang.RuntimeException" message="Test execution failed!">
      <![CDATA[java.lang.RuntimeException: Test execution failed!
at com.tests.scenario5.TC_01_ChkOutFunc_ValidateCheckoutFunctionalityTest.verifyCheckoutFunctionlity(TC_01_ChkOutFunc_ValidateCheckoutFunctionalityTest.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.warning(String)" because "this.extentTest" is null
at com.utilities.ActionLogger.logStep(ActionLogger.java:35)
at com.pageObjects.LoginPage.enterEmail(LoginPage.java:43)
at com.tests.scenario5.TC_01_ChkOutFunc_ValidateCheckoutFunctionalityTest.verifyCheckoutFunctionlity(TC_01_ChkOutFunc_ValidateCheckoutFunctionalityTest.java:29)
... 26 more
]]>
    </failure>
  </testcase> <!-- verifyCheckoutFunctionlity -->
</testsuite> <!-- Default test -->
